# Generated by Django 6.0.6 on 2026-07-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlisting',
            name='district',
            field=models.CharField(choices=[('KASARAGOD', 'Kasaragod'), ('KANNUR', 'Kannur'), ('WAYANAD', 'Wayanad'), ('KOZHIKODE', 'Kozhikode'), ('MALAPPURAM', 'Malappuram'), ('PALAKKAD', 'Palakkad'), ('THRISSUR', 'Thrissur'), ('ERNAKULAM', 'Ernakulam'), ('IDUKKI', 'Idukki'), ('KOTTAYAM', 'Kottayam'), ('ALAPPUZHA', 'Alappuzha'), ('PATHANAMTHITTA', 'Pathanamthitta'), ('KOLLAM', 'Kollam'), ('THIRUVANANTHAPURAM', 'Thiruvananthapuram')], max_length=30, null=True),
        ),
    ]
