# Generated by Django 6.0.6 on 2026-09-20 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_foodlisting_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='price_at_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='seller',
        ),
    ]
